### ISSUE TITLE
GPU implementation of corrField, "MST"

### ISSUE THREAD

**Issue by sirfoga** [multimodallearning/graphregnet#3]
Thank you for your great work. I'm a researched in medical image registration, and would like to ask if you can provide the GPU implementation of corrField, called "MST" in the original paper.

I've only found a PyTorch implementation here: https://grand-challenge.org/algorithms/corrfield/

Thank you!

**Comment by mattiaspaul** [comment]
Thanks for your interest. That version you found is GPU accelerated.

**Comment by sirfoga** [comment]
Thank you for your quick response :) Have you tried already using (pre-trained) SuperGlue [Sarlin et al., 2020] on corrField correspondences?

[Sarlin et al., 2020] Sarlin, P. -E., DeTone, D., Malisiewicz, T., and Rabinovich, A.
“Superglue: Learning Feature Matching with Graph Neural Networks”. In: Inter-
national Conference on Computer Vision and Pattern Recognition –CVPR 2020.
2020, pp. 4938–4947.
